// <auto-generated />
using System;
using AUT2Services.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AUT2Services.Infra.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(AUT2ServicesContext))]
    [Migration("20251203143656_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AUT2Services.Domain.Entities.AutenticadorExterno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("AutenticadorExternoBase")
                        .HasColumnType("bit")
                        .HasColumnName("AutenticadorExternoBase");

                    b.Property<string>("ClaveDeAcceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClaveDeAcceso");

                    b.Property<Guid>("Id_Proveedor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Proveedor");

                    b.Property<Guid>("Id_Usuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Usuario");

                    b.Property<string>("NombreADesplegar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreADesplegar");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NombreUsuario");

                    b.Property<bool>("ValidadorPrimario")
                        .HasColumnType("bit")
                        .HasColumnName("ValidadorPrimario");

                    b.HasKey("Id")
                        .HasName("PK_AutenticadorExterno_Id");

                    b.ToTable("AutenticadorExterno");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecaf1074-722d-468f-81fa-69c2d7b88d68"),
                            Activo = true,
                            AutenticadorExternoBase = true,
                            ClaveDeAcceso = "AQAAAAIAAYagAAAAEJ4PR5McQ5LU8RXggNqnBrS3qdIO54mYO8+1rkT1vSryd4FBlMVPKuLbopBp0XUJKw==",
                            Id_Proveedor = new Guid("701c19bf-405c-4467-85f0-ddbc3786f9ee"),
                            Id_Usuario = new Guid("2b12d04f-c167-4ad1-a42a-e2ecd30518d7"),
                            NombreADesplegar = "ADMINISTRADOR",
                            NombreUsuario = "ADMINISTRADOR",
                            ValidadorPrimario = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Entidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<bool>("EntidadBase")
                        .HasColumnType("bit")
                        .HasColumnName("EntidadBase");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTimeOffset>("FechaInicioAutorizacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaInicioAutorizacion");

                    b.Property<DateTimeOffset>("FechaTerminoAutorizacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaTerminoAutorizacion");

                    b.Property<Guid>("Id_UnidadOrganizacional")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_UnidadOrganizacional");

                    b.Property<Guid>("Id_Usuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Usuario");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit")
                        .HasColumnName("Principal");

                    b.Property<string>("TipoDeEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TipoDeEntidad");

                    b.HasKey("Id")
                        .HasName("PK_Entidad_Id");

                    b.ToTable("Entidad");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            CorreoElectronico = "",
                            EntidadBase = true,
                            FechaCreacion = new DateTimeOffset(new DateTime(2025, 12, 3, 11, 36, 56, 571, DateTimeKind.Unspecified).AddTicks(1214), new TimeSpan(0, -3, 0, 0, 0)),
                            FechaInicioAutorizacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAutorizacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_UnidadOrganizacional = new Guid("198c164d-1cd8-4107-9db3-74b9fa33302c"),
                            Id_Usuario = new Guid("2b12d04f-c167-4ad1-a42a-e2ecd30518d7"),
                            Principal = true,
                            TipoDeEntidad = "UNIDAD_ORGANIZACIONAL"
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Organizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("IdOrganizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdOrganizacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("OrganizacionBase")
                        .HasColumnType("bit")
                        .HasColumnName("OrganizacionBase");

                    b.HasKey("Id")
                        .HasName("PK_Organizacion_Id");

                    b.ToTable("Organizacion");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70c699b4-eb37-49a4-9dcf-1fc87be16489"),
                            Activo = true,
                            Codigo = "ANID",
                            Descripcion = "Entidad pública encargada de promover la investigación y el desarrollo en Chile.",
                            IdOrganizacion = "",
                            Nombre = "Agencia Nacional de Investigación y Desarrollo",
                            OrganizacionBase = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.PoliticaAsignada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTimeOffset>("FechaInicioAsignacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaInicioAsignacion");

                    b.Property<DateTimeOffset>("FechaTerminoAsignacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaTerminoAsignacion");

                    b.Property<Guid>("Id_Entidad")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Entidad");

                    b.Property<Guid>("Id_Proceso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Proceso");

                    b.Property<Guid>("Id_Rol")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Rol");

                    b.Property<bool>("PoliticaAsignadaBase")
                        .HasColumnType("bit")
                        .HasColumnName("PoliticaAsignadaBase");

                    b.Property<bool>("RolAsignadoValidado")
                        .HasColumnType("bit")
                        .HasColumnName("RolAsignadoValidado");

                    b.Property<bool>("RolRequiereValidacion")
                        .HasColumnType("bit")
                        .HasColumnName("RolRequiereValidacion");

                    b.HasKey("Id")
                        .HasName("PK_PoliticaAsignada_Id");

                    b.ToTable("PoliticaAsignada");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f589ba2-3bc0-40ea-b7c2-7aaaee278d6d"),
                            FechaCreacion = new DateTimeOffset(new DateTime(2025, 12, 3, 14, 36, 56, 571, DateTimeKind.Unspecified).AddTicks(3775), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicioAsignacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAsignacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_Entidad = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            Id_Proceso = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Id_Rol = new Guid("c42e4c85-2b6d-4c8f-8672-f82a2d1c2d9e"),
                            PoliticaAsignadaBase = true,
                            RolAsignadoValidado = true,
                            RolRequiereValidacion = false
                        },
                        new
                        {
                            Id = new Guid("bf05f4af-4bbc-472f-a7ed-bbd6d5d1af61"),
                            FechaCreacion = new DateTimeOffset(new DateTime(2025, 12, 3, 14, 36, 56, 571, DateTimeKind.Unspecified).AddTicks(5027), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicioAsignacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAsignacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_Entidad = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            Id_Proceso = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Id_Rol = new Guid("03b6b706-a24f-4505-9ef6-e3ae7d48c907"),
                            PoliticaAsignadaBase = true,
                            RolAsignadoValidado = true,
                            RolRequiereValidacion = false
                        },
                        new
                        {
                            Id = new Guid("60838d42-c2df-402c-9253-ab3ce52ffb55"),
                            FechaCreacion = new DateTimeOffset(new DateTime(2025, 12, 3, 14, 36, 56, 571, DateTimeKind.Unspecified).AddTicks(5033), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicioAsignacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAsignacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_Entidad = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            Id_Proceso = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Id_Rol = new Guid("856a08fd-4162-47cb-bf92-ff25029f3546"),
                            PoliticaAsignadaBase = true,
                            RolAsignadoValidado = true,
                            RolRequiereValidacion = false
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Proceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("ComoDesplegarUrlDeProceso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ComoDesplegarUrlDeProceso");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Contexto");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<Guid>("IdMacro_Proceso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdMacro_Proceso");

                    b.Property<int>("MaximaAsignacionDeRoles")
                        .HasColumnType("int")
                        .HasColumnName("MaximaAsignacionDeRoles");

                    b.Property<string>("NivelDeProceso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NivelDeProceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("ProcesoBase")
                        .HasColumnType("bit")
                        .HasColumnName("ProcesoBase");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Token");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.HasKey("Id")
                        .HasName("PK_Proceso_Id");

                    b.ToTable("Proceso");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Activo = true,
                            Codigo = "ADMINISTRACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Administtracion de Permisos",
                            Descripcion = "Manejo y asignacion de autorizaciones a los usuarios",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 0,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Autorización",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            Activo = true,
                            Codigo = "POSTULACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Postulaciones",
                            Descripcion = "Proceso de Postulacion",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Proceso de Postulacion",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("afc327c0-3970-40c7-9ef6-c0a3fdb42cb9"),
                            Activo = true,
                            Codigo = "POS_CONVOCATORIA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Postulaciones Convocatoria",
                            Descripcion = "Proceso de Postulacion Convocatoria",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Proceso de Postulacion Convocatoria",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("3f5cceaf-4c86-4495-90b4-aafe7c4ab509"),
                            Activo = true,
                            Codigo = "POS_POSTULAR",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Postulaciones Postular",
                            Descripcion = "Proceso de Postulacion Postular",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Proceso de Postulacion Postular",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("c6b401ab-5164-43cc-8ae4-28ca2c9edbbe"),
                            Activo = true,
                            Codigo = "POS_PATROCINIO_INSTITUCIONAL",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Postulaciones Patrocinio Institucional",
                            Descripcion = "Proceso de Postulacion Patrocinio Institucional",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Proceso de Postulacion Patrocinio Institucional",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("a6ef77f1-e26b-430d-9d94-eef157e4df65"),
                            Activo = true,
                            Codigo = "POS_CARTAS_DE_RECOMENDACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Postulaciones Cartas de recomendación",
                            Descripcion = "Proceso de Postulacion Cartas de recomendación",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Proceso de Postulacion Cartas de recomendación",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            Activo = true,
                            Codigo = "SELECCION_FORMALIZACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seleccion y Autorizacion",
                            Descripcion = "Sistema de Seleccion y Autorizacion",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Seleccion y Autorizacion",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("6bd742e3-0e0a-4990-b51f-661c710ba4b9"),
                            Activo = true,
                            Codigo = "SFO_ADMISIBILIDAD",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seleccion y Autorizacion Admisibilidad",
                            Descripcion = "Sistema de Seleccion y Autorizacion Admisibilidad",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seleccion y Autorizacion Admisibilidad",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("7faa600f-2f47-4168-9a65-3c6d47ef2241"),
                            Activo = true,
                            Codigo = "SFO_EVALUACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seleccion y Autorizacion Evaluacion",
                            Descripcion = "Sistema de Seleccion y Autorizacion Evaluacion",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seleccion y Autorizacion Evaluacion",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("5eeb676d-b3fc-4db7-9421-358a6c26d3dc"),
                            Activo = true,
                            Codigo = "SFO_FALLO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seleccion y Autorizacion Fallo",
                            Descripcion = "Sistema de Seleccion y Autorizacion Fallo",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seleccion y Autorizacion Fallo",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("f78ccd33-9762-4beb-83bc-7f2b02a295d7"),
                            Activo = true,
                            Codigo = "SFO_FIRMA_CONVENIO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seleccion y Autorizacion Firma de Convenio",
                            Descripcion = "Sistema de Seleccion y Autorizacion Firma de Convenio",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seleccion y Autorizacion Firma de Convenio",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            Activo = true,
                            Codigo = "SEGUIMIENTO_FINANCIERO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seguimiento Financiero",
                            Descripcion = "Sistema de Seguimiento Financiero",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Seguimiento Financiero",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("e256405c-0bda-479a-8a41-a043c672f9b1"),
                            Activo = true,
                            Codigo = "SFI_PROYECTOS_PRESUPUESTO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seguimiento Financiero Proyectos y Presupuesto",
                            Descripcion = "Sistema de Seguimiento Financiero Proyectos y Presupuesto",
                            IdMacro_Proceso = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seguimiento Financiero Proyectos y Presupuesto",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("2b597b09-55ad-4304-b57d-76bd2df5ac4c"),
                            Activo = true,
                            Codigo = "SFI_RENDICIONES",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seguimiento Financiero Rendiciones",
                            Descripcion = "Sistema de Seguimiento Financiero Rendiciones",
                            IdMacro_Proceso = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seguimiento Financiero Rendiciones",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            Activo = true,
                            Codigo = "SEGUIMIENTO_TECNICO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seguimiento Técnico",
                            Descripcion = "Sistema de Seguimiento Técnico",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Seguimiento Técnico",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("f2224186-ffcc-41ee-bbce-4bbd72504e22"),
                            Activo = true,
                            Codigo = "STE_PROYECTOS_INFORMES",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seguimiento Técnico Proyectos e Informes",
                            Descripcion = "Sistema de Seguimiento Técnico Proyectos e Informes",
                            IdMacro_Proceso = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seguimiento Técnico Proyectos e Informes",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            Activo = true,
                            Codigo = "PRODUCTIVIDAD_CIENTÍFICA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Productividad Científica",
                            Descripcion = "Sistema de Productividad Científica",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Productividad Científica",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("eec159f1-9ba9-463d-8407-ec2951751c29"),
                            Activo = true,
                            Codigo = "PSC_PORTAL_DEL_INVESTIGADOR",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Productividad Científica Portal del Investigador",
                            Descripcion = "Sistema de Productividad Científica Portal del Investigador",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Productividad Científica Portal del Investigador",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("4bb69d17-cc38-4e52-ad36-42226aa5723d"),
                            Activo = true,
                            Codigo = "PSC_REPOSITORIO_ANID",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Productividad Científica Repositorio ANID",
                            Descripcion = "Sistema de Productividad Científica Repositorio ANID",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Productividad Científica Repositorio ANID",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("a4ebe253-17c4-4a98-a333-d6fee919a212"),
                            Activo = true,
                            Codigo = "PSC_DATOS_ABIERTOS",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Productividad Científica Datos Abiertos",
                            Descripcion = "Sistema de Productividad Científica Datos Abiertos",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Productividad Científica Datos Abiertos",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("ed685882-0d73-4fe4-986c-b34f9641622c"),
                            Activo = true,
                            Codigo = "EXPEDIENTE",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Expediente Electrónico",
                            Descripcion = "Sistema de Expediente Electrónico",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Expediente Electrónico",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("7f618ddf-cadc-4955-b97f-31ebb43cac6f"),
                            Activo = true,
                            Codigo = "EXP_EXPEDIENTE_ELECTRONICO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Expediente Electrónico Expediente",
                            Descripcion = "Sistema de Expediente Electrónico Expediente",
                            IdMacro_Proceso = new Guid("ed685882-0d73-4fe4-986c-b34f9641622c"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Expediente Electrónico Expediente",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("APIDeAutenticacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("APIDeAutenticacion");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("ProveedorBase")
                        .HasColumnType("bit")
                        .HasColumnName("ProveedorBase");

                    b.HasKey("Id")
                        .HasName("PK_Proveedor_Id");

                    b.ToTable("Proveedor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d9b40fa-fecb-41f6-ad4f-8ed7ceb1be13"),
                            APIDeAutenticacion = "https://api.claveunica.gob.cl",
                            Activo = true,
                            Codigo = "CLAVEUNICA",
                            Descripcion = "Proveedor de autenticación del gobierno chileno para servicios públicos.",
                            Nombre = "Clave Única",
                            ProveedorBase = true
                        },
                        new
                        {
                            Id = new Guid("701c19bf-405c-4467-85f0-ddbc3786f9ee"),
                            APIDeAutenticacion = "https://www.aut2.darksidetech.services/",
                            Activo = true,
                            Codigo = "ANID",
                            Descripcion = "Proveedor de autenticación implementadop or ANID.",
                            Nombre = "ANID",
                            ProveedorBase = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.UnidadOrganizacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<Guid>("Id_Organizacion")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Organizacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("UnidadOrganizacionalBase")
                        .HasColumnType("bit")
                        .HasColumnName("UnidadOrganizacionalBase");

                    b.HasKey("Id")
                        .HasName("PK_UnidadOrganizacional_Id");

                    b.ToTable("UnidadOrganizacional");

                    b.HasData(
                        new
                        {
                            Id = new Guid("198c164d-1cd8-4107-9db3-74b9fa33302c"),
                            Activo = true,
                            Codigo = "CASA_MATRIZ",
                            Descripcion = "Casa Matriz de la Agencia Nacional de Investigación y Desarrollo",
                            Id_Organizacion = new Guid("70c699b4-eb37-49a4-9dcf-1fc87be16489"),
                            Nombre = "Casa Matriz ANID",
                            UnidadOrganizacionalBase = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.ValidacionEnrrolamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("EnrrolamientoAceptado")
                        .HasColumnType("bit")
                        .HasColumnName("EnrrolamientoAceptado");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaRegistro");

                    b.Property<DateTimeOffset>("FechaValidacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FechaValidacion");

                    b.Property<Guid>("IdValidaEnrrolamiento_Usuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdValidaEnrrolamiento_Usuario");

                    b.Property<Guid>("IdValidado_Usuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdValidado_Usuario");

                    b.HasKey("Id")
                        .HasName("PK_ValidacionEnrrolamiento_Id");

                    b.ToTable("ValidacionEnrrolamiento");
                });

            modelBuilder.Entity("AUT2Services.Domain.Security.Entities.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_Rol");

                    b.Property<bool?>("ActivaDetalleDeAutorizaciones")
                        .HasColumnType("bit");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreNormalizado");

                    b.Property<bool?>("RequiereAccionParaSerAsignado")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiereValidacionDeAsignacion")
                        .HasColumnType("bit");

                    b.Property<bool?>("RolBase")
                        .HasColumnType("bit");

                    b.Property<bool?>("ValidaAsignacionDeRoles")
                        .HasColumnType("bit");

                    b.Property<bool?>("ValidaEnrrolamiento")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NombreNormalizado] IS NOT NULL");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c42e4c85-2b6d-4c8f-8672-f82a2d1c2d9e",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "ADMINISTRADOR",
                            NormalizedName = "ADMINISTRADOR",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "36957ec2-2857-4101-a81b-f0340bf8eff2",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "ADMINISTRADOR_ENTIDAD",
                            NormalizedName = "ADMINISTRADOR_ENTIDAD",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "e3093727-b36b-45af-a495-7c3d0804c0e9",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "ADMINISTRADOR_UNIDAD",
                            NormalizedName = "ADMINISTRADOR_UNIDAD",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "03b6b706-a24f-4505-9ef6-e3ae7d48c907",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "VALIDA_ASIGNACION_ROLES",
                            NormalizedName = "VALIDA_ASIGNACION_ROLES",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "856a08fd-4162-47cb-bf92-ff25029f3546",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "VALIDA_ENRROLAMIENTO",
                            NormalizedName = "VALIDA_ENRROLAMIENTO",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "e198ec28-2b1b-48b0-8d5e-eb946d596e90",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "USUARIO",
                            NormalizedName = "USUARIO",
                            RequiereAccionParaSerAsignado = false,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Security.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadDeAccesosFallidos");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("CorreoElectronicoConfirmado");

                    b.Property<string>("EstadoDeUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacionAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreADesplegar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CorreoElectronicoNormalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuarioNormalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HashDeLaClave");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumeroDeTelefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("NumeroDeTelefonoConfirmado");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RequiereValidacionEnrrolamiento")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("DobleFactorHabilitado");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuario");

                    b.Property<bool?>("UsuarioBase")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NombreUsuarioNormalizado] IS NOT NULL");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2b12d04f-c167-4ad1-a42a-e2ecd30518d7",
                            AccessFailedCount = 10,
                            Activo = true,
                            ConcurrencyStamp = "72e725ba-e2c5-42d3-8fb9-4b7949c73c47",
                            Descripcion = "Administrador global",
                            Email = "administrador@security.com",
                            EmailConfirmed = true,
                            EstadoDeUsuario = "REGISTRADO",
                            IdPersona = "",
                            InformacionAdicional = "",
                            LockoutEnabled = false,
                            NombreADesplegar = "Administrador",
                            NormalizedEmail = "ADMINISTRADOR@SECURITY.COM",
                            NormalizedUserName = "ADMINISTRADOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4PR5McQ5LU8RXggNqnBrS3qdIO54mYO8+1rkT1vSryd4FBlMVPKuLbopBp0XUJKw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RequiereValidacionEnrrolamiento = false,
                            SecurityStamp = "",
                            TipoDeUsuario = "NACIONAL",
                            TwoFactorEnabled = false,
                            UserName = "ADMINISTRADOR",
                            UsuarioBase = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
