services:
  api:
    image: anid-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - .env.container
    environment:
      ASPNETCORE_ENVIRONMENT: Container
      ASPNETCORE_URLS: http://0.0.0.0:5002
      ASPNETCORE_HTTP_PORTS: "5002"
      HTTP_PORTS: "5002"

      # JWT
      JwtOptions__Key: ${JWT_OPTIONS_KEY}
      JwtOptions__Issuer: ${JWT_OPTIONS_ISSUER}
      JwtOptions__Audience: ${JWT_OPTIONS_AUDIENCE}

      # PostgreSQL
      ConnectionStrings__AUT2ServicesConnectionPostgreSql: ${POSTGRES_CONNECTION_STRING}

      # Mongo
      MongoAuditProjection__ConnectionString: ${MONGO_CONNECTION_STRING}

      # Email
      SendEmailOptions__SmtpClient: ${SMTP_CLIENT}
      SendEmailOptions__Port: ${SMTP_PORT}
      SendEmailOptions__Remitente: ${SMTP_REMITENTE}
      SendEmailOptions__Password: ${SMTP_PASSWORD}
      SendEmailOptions__EnableSsl: ${SMTP_ENABLE_SSL}

      # Zendesk
      ZendeskSendTicketOptions__Subdomain: ${ZENDESK_SUBDOMAIN}
      ZendeskSendTicketOptions__Email: ${ZENDESK_EMAIL}
      ZendeskSendTicketOptions__ApiToken: ${ZENDESK_API_TOKEN}
      ZendeskSendTicketOptions__ApiUri: ${ZENDESK_API_URI}
