<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.325.26068</AssemblyVersion>
    <FileVersion>1.0.325.26068</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AUT2Services.Domain.Core\AUT2Services.Domain.Core.csproj" />
  </ItemGroup>

</Project>
