// <auto-generated />
using System;
using AUT2Services.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AUT2Services.Infra.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(AUT2ServicesContext))]
    [Migration("20260406234227_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AUT2Services.Domain.Entities.AutenticadorExterno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("AutenticadorExternoBase")
                        .HasColumnType("boolean")
                        .HasColumnName("AutenticadorExternoBase");

                    b.Property<string>("ClaveDeAcceso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ClaveDeAcceso");

                    b.Property<Guid>("Id_Proveedor")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_Proveedor");

                    b.Property<Guid>("Id_Usuario")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_Usuario");

                    b.Property<string>("NombreADesplegar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreADesplegar");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NombreUsuario");

                    b.Property<bool>("ValidadorPrimario")
                        .HasColumnType("boolean")
                        .HasColumnName("ValidadorPrimario");

                    b.HasKey("Id")
                        .HasName("PK_AutenticadorExterno_Id");

                    b.ToTable("AutenticadorExterno");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecaf1074-722d-468f-81fa-69c2d7b88d68"),
                            Activo = true,
                            AutenticadorExternoBase = true,
                            ClaveDeAcceso = "AQAAAAIAAYagAAAAEI6x2Zir3U9izF0j0aIsdPjRT/G72/zAZedaz0ieb0sdgpqH6ooegTLinxwcsIPliQ==",
                            Id_Proveedor = new Guid("701c19bf-405c-4467-85f0-ddbc3786f9ee"),
                            Id_Usuario = new Guid("2b12d04f-c167-4ad1-a42a-e2ecd30518d7"),
                            NombreADesplegar = "ADMINISTRADOR",
                            NombreUsuario = "ADMINISTRADOR",
                            ValidadorPrimario = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Entidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CorreoElectronico");

                    b.Property<bool>("EntidadBase")
                        .HasColumnType("boolean")
                        .HasColumnName("EntidadBase");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTimeOffset>("FechaInicioAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicioAutorizacion");

                    b.Property<DateTimeOffset>("FechaTerminoAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaTerminoAutorizacion");

                    b.Property<Guid>("Id_UnidadOrganizacional")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_UnidadOrganizacional");

                    b.Property<Guid>("Id_Usuario")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_Usuario");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("Principal");

                    b.Property<string>("TipoDeEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TipoDeEntidad");

                    b.HasKey("Id")
                        .HasName("PK_Entidad_Id");

                    b.ToTable("Entidad");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            CorreoElectronico = "",
                            EntidadBase = true,
                            FechaCreacion = new DateTimeOffset(new DateTime(2026, 4, 6, 19, 42, 27, 433, DateTimeKind.Unspecified).AddTicks(847), new TimeSpan(0, -4, 0, 0, 0)),
                            FechaInicioAutorizacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAutorizacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_UnidadOrganizacional = new Guid("198c164d-1cd8-4107-9db3-74b9fa33302c"),
                            Id_Usuario = new Guid("2b12d04f-c167-4ad1-a42a-e2ecd30518d7"),
                            Principal = true,
                            TipoDeEntidad = "UNIDAD_ORGANIZACIONAL"
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Organizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("IdOrganizacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IdOrganizacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("OrganizacionBase")
                        .HasColumnType("boolean")
                        .HasColumnName("OrganizacionBase");

                    b.HasKey("Id")
                        .HasName("PK_Organizacion_Id");

                    b.ToTable("Organizacion");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70c699b4-eb37-49a4-9dcf-1fc87be16489"),
                            Activo = true,
                            Codigo = "ANID",
                            Descripcion = "Entidad pública encargada de promover la investigación y el desarrollo en Chile.",
                            IdOrganizacion = "",
                            Nombre = "Agencia Nacional de Investigación y Desarrollo",
                            OrganizacionBase = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.PoliticaAsignada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTimeOffset>("FechaInicioAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicioAsignacion");

                    b.Property<DateTimeOffset>("FechaTerminoAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaTerminoAsignacion");

                    b.Property<Guid>("Id_Entidad")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_Entidad");

                    b.Property<Guid>("Id_Proceso")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_Proceso");

                    b.Property<Guid>("Id_Rol")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_Rol");

                    b.Property<bool>("PoliticaAsignadaBase")
                        .HasColumnType("boolean")
                        .HasColumnName("PoliticaAsignadaBase");

                    b.Property<bool>("RolAsignadoValidado")
                        .HasColumnType("boolean")
                        .HasColumnName("RolAsignadoValidado");

                    b.Property<bool>("RolRequiereValidacion")
                        .HasColumnType("boolean")
                        .HasColumnName("RolRequiereValidacion");

                    b.HasKey("Id")
                        .HasName("PK_PoliticaAsignada_Id");

                    b.ToTable("PoliticaAsignada");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f589ba2-3bc0-40ea-b7c2-7aaaee278d6d"),
                            FechaCreacion = new DateTimeOffset(new DateTime(2026, 4, 6, 23, 42, 27, 434, DateTimeKind.Unspecified).AddTicks(9061), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicioAsignacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAsignacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_Entidad = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            Id_Proceso = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Id_Rol = new Guid("c42e4c85-2b6d-4c8f-8672-f82a2d1c2d9e"),
                            PoliticaAsignadaBase = true,
                            RolAsignadoValidado = true,
                            RolRequiereValidacion = false
                        },
                        new
                        {
                            Id = new Guid("bf05f4af-4bbc-472f-a7ed-bbd6d5d1af61"),
                            FechaCreacion = new DateTimeOffset(new DateTime(2026, 4, 6, 23, 42, 27, 435, DateTimeKind.Unspecified).AddTicks(282), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicioAsignacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAsignacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_Entidad = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            Id_Proceso = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Id_Rol = new Guid("03b6b706-a24f-4505-9ef6-e3ae7d48c907"),
                            PoliticaAsignadaBase = true,
                            RolAsignadoValidado = true,
                            RolRequiereValidacion = false
                        },
                        new
                        {
                            Id = new Guid("60838d42-c2df-402c-9253-ab3ce52ffb55"),
                            FechaCreacion = new DateTimeOffset(new DateTime(2026, 4, 6, 23, 42, 27, 435, DateTimeKind.Unspecified).AddTicks(291), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicioAsignacion = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaTerminoAsignacion = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            Id_Entidad = new Guid("05507441-5792-4c46-9334-9a5faa99e20a"),
                            Id_Proceso = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Id_Rol = new Guid("856a08fd-4162-47cb-bf92-ff25029f3546"),
                            PoliticaAsignadaBase = true,
                            RolAsignadoValidado = true,
                            RolRequiereValidacion = false
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Proceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("ComoDesplegarUrlDeProceso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ComoDesplegarUrlDeProceso");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Contexto");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<Guid>("IdMacro_Proceso")
                        .HasColumnType("uuid")
                        .HasColumnName("IdMacro_Proceso");

                    b.Property<int>("MaximaAsignacionDeRoles")
                        .HasColumnType("integer")
                        .HasColumnName("MaximaAsignacionDeRoles");

                    b.Property<string>("NivelDeProceso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NivelDeProceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("ProcesoBase")
                        .HasColumnType("boolean")
                        .HasColumnName("ProcesoBase");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Token");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Url");

                    b.HasKey("Id")
                        .HasName("PK_Proceso_Id");

                    b.ToTable("Proceso");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1889c7c-c5dc-4d9a-a2fe-34cdf956b145"),
                            Activo = true,
                            Codigo = "ADMINISTRACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Administtracion de Permisos",
                            Descripcion = "Manejo y asignacion de autorizaciones a los usuarios",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 0,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Autorización",
                            ProcesoBase = true,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            Activo = true,
                            Codigo = "POSTULACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Postulaciones",
                            Descripcion = "Proceso de Postulacion",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Proceso de Postulacion",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("afc327c0-3970-40c7-9ef6-c0a3fdb42cb9"),
                            Activo = true,
                            Codigo = "POS_ACONCAGUA_SPI",
                            ComoDesplegarUrlDeProceso = "REDIRECCION",
                            Contexto = "Sistema Aconcagua SPI",
                            Descripcion = "Sistema Aconcagua SPI",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Aconcagua SPI",
                            ProcesoBase = false,
                            Token = "",
                            Url = "https://auth-qa01.anid.cl"
                        },
                        new
                        {
                            Id = new Guid("3f5cceaf-4c86-4495-90b4-aafe7c4ab509"),
                            Activo = true,
                            Codigo = "POS_ACONCAGUA_GENERICO",
                            ComoDesplegarUrlDeProceso = "REDIRECCION",
                            Contexto = "Sistema Aconcagua generico",
                            Descripcion = "Sistema Aconcagua Generico",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Aconcagua Generico",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://auth-qa05.anid.cl"
                        },
                        new
                        {
                            Id = new Guid("c6b401ab-5164-43cc-8ae4-28ca2c9edbbe"),
                            Activo = true,
                            Codigo = "POS_GENESIS",
                            ComoDesplegarUrlDeProceso = "REDIRECCION",
                            Contexto = "Sistema Genesis",
                            Descripcion = "Sistema Genesis",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Genesis",
                            ProcesoBase = false,
                            Token = "",
                            Url = "https://splqa.anid.cl"
                        },
                        new
                        {
                            Id = new Guid("a6ef77f1-e26b-430d-9d94-eef157e4df65"),
                            Activo = true,
                            Codigo = "POS_MILENIO",
                            ComoDesplegarUrlDeProceso = "REDIRECCION",
                            Contexto = "Sistema de Postulaciones Milenio",
                            Descripcion = "Proceso de Postulacion Milenio",
                            IdMacro_Proceso = new Guid("233783de-9094-4030-907d-82d7c5abf10e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Proceso de Postulacion Milenio",
                            ProcesoBase = false,
                            Token = "",
                            Url = "https://post-im.conicyt.cl/Concursos"
                        },
                        new
                        {
                            Id = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            Activo = true,
                            Codigo = "SELECCION_FORMALIZACION",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seleccion y Formalizacion",
                            Descripcion = "Sistema de Seleccion y Formalizacion",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Seleccion y Formalizacion",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("6bd742e3-0e0a-4990-b51f-661c710ba4b9"),
                            Activo = true,
                            Codigo = "SFO_EVAL_SPI",
                            ComoDesplegarUrlDeProceso = "VENTANA",
                            Contexto = "Sistema Eval SPI",
                            Descripcion = "Sistema Eval SPI",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Eval SPI",
                            ProcesoBase = false,
                            Token = "",
                            Url = "https://faraondesa.anid.cl/desa2/Evaluacion_TESTING/index.php"
                        },
                        new
                        {
                            Id = new Guid("7faa600f-2f47-4168-9a65-3c6d47ef2241"),
                            Activo = true,
                            Codigo = "SFO_EVAL_BECAS",
                            ComoDesplegarUrlDeProceso = "VENTANA",
                            Contexto = "Sistema Eval Becas",
                            Descripcion = "Sistema Eval Becas",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Eval Becas",
                            ProcesoBase = false,
                            Token = "",
                            Url = "https://servicios-qa.anid.cl/evalbecas"
                        },
                        new
                        {
                            Id = new Guid("5eeb676d-b3fc-4db7-9421-358a6c26d3dc"),
                            Activo = true,
                            Codigo = "SFO_EVAL_GENERICO",
                            ComoDesplegarUrlDeProceso = "VENTANA",
                            Contexto = "Sistema Eval Generico",
                            Descripcion = "Sistema Eval Generico",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Eval Generico",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("f78ccd33-9762-4beb-83bc-7f2b02a295d7"),
                            Activo = true,
                            Codigo = "SFO_FIRMA_CONVENIO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seleccion y Autorizacion Firma de Convenio",
                            Descripcion = "Sistema de Seleccion y Autorizacion Firma de Convenio",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema de Seleccion y Autorizacion Firma de Convenio",
                            ProcesoBase = false,
                            Token = "",
                            Url = "https://servicios-qa.anid.cl/web/firma-convenio/#/login"
                        },
                        new
                        {
                            Id = new Guid("9679412f-ae9f-4d77-8629-7559d280ece2"),
                            Activo = true,
                            Codigo = "SFO_FALLO_BECA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Fallo Beca",
                            Descripcion = "Sistema Fallo Beca",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Fallo Beca",
                            ProcesoBase = false,
                            Token = "",
                            Url = "https://servicios-qa.anid.cl/web//fallo/#/public"
                        },
                        new
                        {
                            Id = new Guid("a6151eed-ea81-4edb-9c89-5bf7e260989f"),
                            Activo = true,
                            Codigo = "SFO_FALLO_SPI",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Fallo SPI",
                            Descripcion = "Sistema Fallo SPI",
                            IdMacro_Proceso = new Guid("c4a10de0-791c-45ec-820c-1a8802cd3e80"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Fallo SPI",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            Activo = true,
                            Codigo = "SEGUIMIENTO_TECNICO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seguimiento Técnico",
                            Descripcion = "Sistema de Seguimiento Técnico",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Seguimiento Técnico",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("f2224186-ffcc-41ee-bbce-4bbd72504e22"),
                            Activo = true,
                            Codigo = "STE_SIAL_SPI",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema SIAL SPI",
                            Descripcion = "Sistema SIAL SPI",
                            IdMacro_Proceso = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema SIAL SPI",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("f3285b94-90a4-4610-8c65-2782d2e3a1a3"),
                            Activo = true,
                            Codigo = "STE_SyC_LEGACY_SIA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema SyC Legacy SIA",
                            Descripcion = "Sistema SyC Legacy SIA",
                            IdMacro_Proceso = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema SyC Legacy SIA",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("fa2e0bda-3063-4357-91b5-17f443b74ebd"),
                            Activo = true,
                            Codigo = "STE_SISFON_LUTHIEN_SPI_SCH",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Sisfon Luthien SPI SCH",
                            Descripcion = "Sistema Sisfon Luthien SPI SCH",
                            IdMacro_Proceso = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Sisfon Luthien SPI SCH",
                            ProcesoBase = false,
                            Token = "",
                            Url = "172.16.4.107:22"
                        },
                        new
                        {
                            Id = new Guid("8ff51db1-44a5-4b9e-b0eb-0cd739cee604"),
                            Activo = true,
                            Codigo = "STE_SISTEMA_VERDE_SIA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Verde SIA",
                            Descripcion = "Sistema Verde SIA",
                            IdMacro_Proceso = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Verde SIA",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("e150709d-4fed-480b-8916-8b0837a775d3"),
                            Activo = true,
                            Codigo = "STE_GESTION_MILENIO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Gestion Milenio",
                            Descripcion = "Sistema Gestion Milenio",
                            IdMacro_Proceso = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Gestion Milenio",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("9cc3ac0d-503a-42b1-bc8e-10d20265e15b"),
                            Activo = true,
                            Codigo = "STE_SISTEMA_TERMINO_SIA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Termino SIA",
                            Descripcion = "Sistema Termino SIA",
                            IdMacro_Proceso = new Guid("aeaeb19b-2206-4870-9a99-f5d40a982b2e"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Termino SIA",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            Activo = true,
                            Codigo = "SEGUIMIENTO_FINANCIERO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema de Seguimiento Financiero",
                            Descripcion = "Sistema de Seguimiento Financiero",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema de Seguimiento Financiero",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("e256405c-0bda-479a-8a41-a043c672f9b1"),
                            Activo = true,
                            Codigo = "SFI_SGDL_SPI",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema SDGL SPI",
                            Descripcion = "Sistema SDGL SPI",
                            IdMacro_Proceso = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema SDGL SPI",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("2b597b09-55ad-4304-b57d-76bd2df5ac4c"),
                            Activo = true,
                            Codigo = "SFI_SISFON_LUTHIEN_SPI_SCH",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Sisfon Luthien SPI SCH",
                            Descripcion = "Sistema Sisfon Luthien SPI SCH",
                            IdMacro_Proceso = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Sisfon Luthien SPI SCH",
                            ProcesoBase = false,
                            Token = "",
                            Url = "172.16.4.107:22"
                        },
                        new
                        {
                            Id = new Guid("d65b2a0d-0742-491b-be4f-c7c00219821d"),
                            Activo = true,
                            Codigo = "SFI_SYC_FINANCIERO_SIA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema SyC Financiero SIA",
                            Descripcion = "Sistema SyC Financiero SIA",
                            IdMacro_Proceso = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema SyC Financiero SIA",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("0737dfc9-8c0f-44ed-ada9-0d227d6a4b5c"),
                            Activo = true,
                            Codigo = "SFI_SISTEMA_TERMINO_SIA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Sistema Termino SIA",
                            Descripcion = "Sistema Sistema Termino SIA",
                            IdMacro_Proceso = new Guid("06001a21-9b5f-47a3-ae8b-c749e531f9b1"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Sistema Termino SIA",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            Activo = true,
                            Codigo = "VIN_SCIELO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Scielo",
                            Descripcion = "Sistema Scielo",
                            IdMacro_Proceso = new Guid("00000000-0000-0000-0000-000000000000"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_MACRO",
                            Nombre = "Sistema Scielo",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("eec159f1-9ba9-463d-8407-ec2951751c29"),
                            Activo = true,
                            Codigo = "VIN_SCIELO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Scielo",
                            Descripcion = "Sistema Scielo",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Scielo",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("4bb69d17-cc38-4e52-ad36-42226aa5723d"),
                            Activo = true,
                            Codigo = "VIN_BEIC",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Beic",
                            Descripcion = "Sistema Beic",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Beic",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("a4ebe253-17c4-4a98-a333-d6fee919a212"),
                            Activo = true,
                            Codigo = "VIN_PDI",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema PDI",
                            Descripcion = "Sistema PDI",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema PDI",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("35e9a345-dda9-45fc-9a35-7cf27ec8e947"),
                            Activo = true,
                            Codigo = "VIN_DATACIENCIA",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema DataCiencia",
                            Descripcion = "Sistema DataCiencia",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema DataCiencia",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("9c4a10ea-d6f3-4a0c-b4b0-25fb0396c7ee"),
                            Activo = true,
                            Codigo = "VIN_REPOSITORIO",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema Repositorio",
                            Descripcion = "Sistema Repositorio",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema Repositorio",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        },
                        new
                        {
                            Id = new Guid("587ec39b-e7d8-4c0f-9ac4-697940cf7b07"),
                            Activo = true,
                            Codigo = "VIN_DIODI",
                            ComoDesplegarUrlDeProceso = "IFRAME",
                            Contexto = "Sistema DIODI",
                            Descripcion = "Sistema DIODI",
                            IdMacro_Proceso = new Guid("fcd2dcf8-7230-4fdd-9651-b4efeb60d11f"),
                            MaximaAsignacionDeRoles = 1,
                            NivelDeProceso = "NIVEL_SISTEMA",
                            Nombre = "Sistema DIODI",
                            ProcesoBase = false,
                            Token = "",
                            Url = "http://localhost:4210"
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("APIDeAutenticacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("APIDeAutenticacion");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("ProveedorBase")
                        .HasColumnType("boolean")
                        .HasColumnName("ProveedorBase");

                    b.HasKey("Id")
                        .HasName("PK_Proveedor_Id");

                    b.ToTable("Proveedor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d9b40fa-fecb-41f6-ad4f-8ed7ceb1be13"),
                            APIDeAutenticacion = "https://api.claveunica.gob.cl",
                            Activo = true,
                            Codigo = "CLAVEUNICA",
                            Descripcion = "Proveedor de autenticación del gobierno chileno para servicios públicos.",
                            Nombre = "Clave Única",
                            ProveedorBase = true
                        },
                        new
                        {
                            Id = new Guid("701c19bf-405c-4467-85f0-ddbc3786f9ee"),
                            APIDeAutenticacion = "https://www.aut2.darksidetech.services/",
                            Activo = true,
                            Codigo = "ANID",
                            Descripcion = "Proveedor de autenticación implementadop or ANID.",
                            Nombre = "ANID",
                            ProveedorBase = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.UnidadOrganizacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<Guid>("Id_Organizacion")
                        .HasColumnType("uuid")
                        .HasColumnName("Id_Organizacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("UnidadOrganizacionalBase")
                        .HasColumnType("boolean")
                        .HasColumnName("UnidadOrganizacionalBase");

                    b.HasKey("Id")
                        .HasName("PK_UnidadOrganizacional_Id");

                    b.ToTable("UnidadOrganizacional");

                    b.HasData(
                        new
                        {
                            Id = new Guid("198c164d-1cd8-4107-9db3-74b9fa33302c"),
                            Activo = true,
                            Codigo = "CASA_MATRIZ",
                            Descripcion = "Casa Matriz de la Agencia Nacional de Investigación y Desarrollo",
                            Id_Organizacion = new Guid("70c699b4-eb37-49a4-9dcf-1fc87be16489"),
                            Nombre = "Casa Matriz ANID",
                            UnidadOrganizacionalBase = true
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Entities.ValidacionEnrrolamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("EnrrolamientoAceptado")
                        .HasColumnType("boolean")
                        .HasColumnName("EnrrolamientoAceptado");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRegistro");

                    b.Property<DateTimeOffset>("FechaValidacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaValidacion");

                    b.Property<Guid>("IdValidaEnrrolamiento_Usuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdValidaEnrrolamiento_Usuario");

                    b.Property<Guid>("IdValidado_Usuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdValidado_Usuario");

                    b.HasKey("Id")
                        .HasName("PK_ValidacionEnrrolamiento_Id");

                    b.ToTable("ValidacionEnrrolamiento");
                });

            modelBuilder.Entity("AUT2Services.Domain.Security.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id_Entidad")
                        .HasColumnType("uuid");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectedOrganization")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AUT2Services.Domain.Security.Entities.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id_Rol");

                    b.Property<bool?>("ActivaDetalleDeAutorizaciones")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NombreNormalizado");

                    b.Property<bool?>("RequiereAccionParaSerAsignado")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RequiereValidacionDeAsignacion")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RolBase")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ValidaAsignacionDeRoles")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ValidaEnrrolamiento")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c42e4c85-2b6d-4c8f-8672-f82a2d1c2d9e",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "ADMINISTRADOR",
                            NormalizedName = "ADMINISTRADOR",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "36957ec2-2857-4101-a81b-f0340bf8eff2",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "ADMINISTRADOR_ENTIDAD",
                            NormalizedName = "ADMINISTRADOR_ENTIDAD",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "e3093727-b36b-45af-a495-7c3d0804c0e9",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "ADMINISTRADOR_UNIDAD",
                            NormalizedName = "ADMINISTRADOR_UNIDAD",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "03b6b706-a24f-4505-9ef6-e3ae7d48c907",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "VALIDA_ASIGNACION_ROLES",
                            NormalizedName = "VALIDA_ASIGNACION_ROLES",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "856a08fd-4162-47cb-bf92-ff25029f3546",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "VALIDA_ENRROLAMIENTO",
                            NormalizedName = "VALIDA_ENRROLAMIENTO",
                            RequiereAccionParaSerAsignado = true,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        },
                        new
                        {
                            Id = "e198ec28-2b1b-48b0-8d5e-eb946d596e90",
                            ActivaDetalleDeAutorizaciones = false,
                            Activo = true,
                            Descripcion = "",
                            Name = "USUARIO",
                            NormalizedName = "USUARIO",
                            RequiereAccionParaSerAsignado = false,
                            RequiereValidacionDeAsignacion = false,
                            RolBase = true,
                            ValidaAsignacionDeRoles = false,
                            ValidaEnrrolamiento = false
                        });
                });

            modelBuilder.Entity("AUT2Services.Domain.Security.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("CantidadDeAccesosFallidos");

                    b.Property<bool?>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("CorreoElectronicoConfirmado");

                    b.Property<string>("EstadoDeUsuario")
                        .HasColumnType("text");

                    b.Property<string>("IdPersona")
                        .HasColumnType("text");

                    b.Property<string>("InformacionAdicional")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreADesplegar")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CorreoElectronicoNormalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NombreUsuarioNormalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("HashDeLaClave");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("NumeroDeTelefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("NumeroDeTelefonoConfirmado");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("RequiereValidacionEnrrolamiento")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TipoDeUsuario")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("DobleFactorHabilitado");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NombreUsuario");

                    b.Property<bool?>("UsuarioBase")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2b12d04f-c167-4ad1-a42a-e2ecd30518d7",
                            AccessFailedCount = 10,
                            Activo = true,
                            ConcurrencyStamp = "a9f4ebf7-5ec4-450f-ab46-a263fe780995",
                            Descripcion = "Administrador global",
                            Email = "administrador@security.com",
                            EmailConfirmed = true,
                            EstadoDeUsuario = "REGISTRADO",
                            IdPersona = "",
                            InformacionAdicional = "",
                            LockoutEnabled = false,
                            NombreADesplegar = "Administrador",
                            NormalizedEmail = "ADMINISTRADOR@SECURITY.COM",
                            NormalizedUserName = "ADMINISTRADOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEI6x2Zir3U9izF0j0aIsdPjRT/G72/zAZedaz0ieb0sdgpqH6ooegTLinxwcsIPliQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RequiereValidacionEnrrolamiento = false,
                            SecurityStamp = "",
                            TipoDeUsuario = "NACIONAL",
                            TwoFactorEnabled = false,
                            UserName = "ADMINISTRADOR",
                            UsuarioBase = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AUT2Services.Domain.Security.Entities.RefreshToken", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AUT2Services.Domain.Security.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AUT2Services.Domain.Security.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
