<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.397.26058</AssemblyVersion>
    <FileVersion>1.0.397.26058</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AUT2Services.Domain\AUT2Services.Domain.csproj" />
    <ProjectReference Include="..\AUT2Services.Infra.Data\AUT2Services.Infra.Data.csproj" />
  </ItemGroup>

</Project>
